version: "3"
services:
  web:
    image: php:8.3.3-apache-bullseye
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
        - .:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: "1m30s"
      retries: 3
    restart: on-failure
